### ISSUE TITLE
Not showing import button on product page?

### ISSUE THREAD

**Issue by RoobiPro** [bagisto/laravel-aliexpress-dropship#20]
The import button on the product page is not showing up.
Is this plugin still working?

Many thanks
Rob

![bagistoplugin](https://user-images.githubusercontent.com/7908718/65932784-354cb880-e439-11e9-8ddc-557d00ff2bd7.jpg)

**Comment by prateek-webkul** [comment]
Hello RoobiPro, 
yes the plugin is working fine .
Have you downloaded the latest extension?
If not refer (https://github.com/bagisto/laravel-aliexpress-dropship-chrome-extension)

**Comment by prateek-webkul** [comment]
Hi RoobiPro,

This issue has been opened for more than a month. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks

**Comment by karthickk3** [comment]
Prateek, it's still not working and I see that most people posted about the same, but nobody got the solution yet. Is it because it's free and so you guys are not providing the solution consciously? ;)
